empleado/aplications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "departamento_app"

urlpatterns = [
    path("new-departamento",
    views.NewDepartamentoView.as_view(),
    name="nuevo-depa"
    ),
    path("lista-by-departamento",
    views.DepartamentoListView.as_view(),
    name="lista-por-depa"
    ),
]

empleado/aplications/persona/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = "persona_app" 

urlpatterns = [
    path(
        "",
        views.InicioView.as_view(),
        name="inicio"
    ),
    path(
        "listar-empleados",
        views.MostrarEmpleados.as_view(),
        name="listar-all"        
    ),
    path("listar-por-departamento/<shorname>",
        views.listar_por_area.as_view(),
        name="empleado-departamento"
    ),
    path("list_all_admin",
        views.MostrarEmpleadosAdmin.as_view(),
        name="list_admin"
    ),
    path("listar-por-trabajo/<laburo>",views.listar_por_trabajo.as_view()),
    path("listar_por_kword/",views.listar_empleado_por_keyword.as_view()),
    path("listar_habilidad/",views.Habilidades_de_Empleados.as_view()),
    path(
        "detalle-vista/<pk>",
        views.EmpleadoDetailView.as_view(),
        name="detalle-empleado"
    ),
    path("agregar-empleado",
    views.EmpleadoCreateView.as_view(),
    name="add-empleado"
    ),
    path("success",views.Successview.as_view(),name="correcto"),
    path("update-empleado/<pk>",
        views.EmpleadoUpdateView.as_view(),
        name="modificar_empleado"
    ),
    path("delete-empleado/<pk>",
    views.EmpleadoDeleteView.as_view(),
    name="borrar-empleado")

]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path,include
#para añadir las urls multimedia
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('aplications.persona.urls')),
    path('',include('aplications.prueba_form.urls')),
    path('',include('aplications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

empleado/templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left" >
      <ul class="dropdown menu" data-dropdown-menu>
        <li>
          <a href="{% url 'persona_app:inicio' %}">Inicio</a>
        </li>
        <li>
          <a href="{% url 'persona_app:listar-all' %}">Listar</a>          
        </li>
        <li><a href="{% url 'departamento_app:lista-por-depa' %}">Departamento</a></li>
        <li><a href="{% url 'persona_app:list_admin' %}">Administrar</a></li>
        <li><a href="{% url 'departamento_app:nuevo-depa' %}">Nuevo departamento</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><a href="{% url 'persona_app:add-empleado' %}" class="button" style="margin: 2px; ">Registrar nuevo empleado</a></li>
      </ul>
    </div>
  </div>