empleado/aplications/persona/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = "persona_app" 

urlpatterns = [
    path(
        "",
        views.InicioView.as_view(),
        name="inicio"
    ),
    path(
        "listar-empleados",
        views.MostrarEmpleados.as_view(),
        name="listar-all"        
    ),
    path("listar-por-departamento/<shorname>",
        views.listar_por_area.as_view(),
        name="empleado-departamento"
    ),
    path("list_all_admin",
        views.MostrarEmpleadosAdmin.as_view(),
        name="list_admin"
    ),
    path("listar-por-trabajo/<laburo>",views.listar_por_trabajo.as_view()),
    path("listar_por_kword/",views.listar_empleado_por_keyword.as_view()),
    path("listar_habilidad/",views.Habilidades_de_Empleados.as_view()),
    path(
        "detalle-vista/<pk>",
        views.EmpleadoDetailView.as_view(),
        name="detalle-empleado"
    ),
    path("agregar-empleado",
    views.EmpleadoCreateView.as_view(),
    name="add-empleado"
    ),
    path("success",views.Successview.as_view(),name="correcto"),
    path("update-empleado/<pk>",
        views.EmpleadoUpdateView.as_view(),
        name="modificar_empleado"
    ),
    path("delete-empleado/<pk>",
    views.EmpleadoDeleteView.as_view(),
    name="borrar-empleado")

]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path,include
#para añadir las urls multimedia
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('aplications.persona.urls')),
    path('',include('aplications.prueba_form.urls')),
    path('',include('aplications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

empleado/aplications/persona/models.py
from django.db import models

from aplications.departamento.models import Departamento

from ckeditor.fields import RichTextField
# Create your models here.

class Habilidad(models.Model):
    habilidad = models.CharField("Habilidad", max_length=50)

    class Meta:
        verbose_name = "Habilidade"
        

    def __str__(self):
        return self.habilidad     



class Empleado(models.Model):
    """ Modelo para tabla empleado"""

    tipo_job = (
        ("0","Contador"),
        ("1","Administrador"),
        ("2","Economista"),
        ("3","Otros"),

    )

    first_name = models.CharField("Nombres", max_length=50)
    last_name = models.CharField("Apellidos", max_length=50)
    job = models.CharField("Trabajo", max_length=1,choices=tipo_job)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    full_name = models.CharField("Full name",max_length=120,blank=True)
    imagen = models.ImageField("Foto", upload_to="empleado", blank=True,null=True)
    habilidades = models.ManyToManyField(Habilidad,blank=True)
    hoja_vida = RichTextField()

    class Meta:
        verbose_name = "Empleados de la empresa"
        ordering = ["first_name"]
        unique_together = ("first_name","last_name","job")


    def __str__(self):
        return str(self.id) + "-" + self.first_name + "-" + self.last_name
        

empleado/aplications/persona/forms.py
from django import forms

from .models import Empleado

class EmpleadoForm(forms.ModelForm):

    class Meta:

        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'imagen',
            'habilidades',
            )

        widgets = {
            "habilidades": forms.CheckboxSelectMultiple()
        }    

empleado/aplications/persona/views.py
from django.shortcuts import render

from django.views.generic import ListView,DetailView,CreateView,TemplateView,UpdateView,DeleteView
from .models import Empleado
from django.urls import reverse_lazy

#forms
from .forms import EmpleadoForm

# Create your views here.

class InicioView(TemplateView):
    #vista que carga la pagina de inicio
    template_name = "inicio.html"

class MostrarEmpleados(ListView):
    template_name = "persona/list_all.html"
    #model = Empleado          "cuando añadimos la funcion get_queryset no se utiliza el modelo"
    context_object_name = "list_emple"
    paginate_by = 4

    def get_queryset(self):

        palabra_clave = self.request.GET.get("kword","")
        lista= Empleado.objects.filter(
            full_name__icontains = palabra_clave
        )       

        return lista 


class MostrarEmpleadosAdmin(ListView):
    template_name = "persona/list_all_admin.html"
    model = Empleado
    context_object_name = "list_admin"
    ordering = "first_name"
    paginate_by = 10



# vistas de practica
class listar_por_area(ListView):
    template_name = "persona/list_by_departamento.html"
    context_object_name = "empleados"
    

    def get_queryset(self):
        area = self.kwargs["shorname"]
        lista= Empleado.objects.filter(
        departamento__short_name = area)

        return lista

class listar_por_trabajo(ListView):
    template_name = "persona/list_por_trabajo.html"
    context_object_name = "list"
    def get_queryset(self):
        
        trabajo = self.kwargs["laburo"]
        liste= Empleado.objects.filter(
            job = trabajo
        )
        
        return liste

class listar_empleado_por_keyword(ListView):
    template_name = "persona/por_kword.html"
    context_object_name = "array_kword"

    def get_queryset(self):

        palabra_clave = self.request.GET.get("kword","")
        lista= Empleado.objects.filter(
            first_name = palabra_clave
        )       

        return lista             

class Habilidades_de_Empleados(ListView):
    template_name = "persona/habilidades.html"
    context_object_name = "hability"

    def get_queryset(self):
        empleado = Empleado.objects.get(id=5)
        
        return empleado.habilidades.all()        


class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detailview.html"

    
    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context["titulo"] = "Soy la mera verga"
        return context



class Successview(TemplateView):
    template_name = "persona/success.html"


class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "persona/agregar.html"
    form_class = EmpleadoForm
    success_url = reverse_lazy('persona_app:list_admin')

    def form_valid(self, form):
        empleado = form.save()
        concatenar = empleado.first_name + " " + empleado.last_name
        empleado.full_name = concatenar
        empleado.save()
        return super(EmpleadoCreateView,self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "persona/update.html"
    fields = (
        "first_name",
        "last_name",
        "job",
        "departamento",
        "habilidades",
    )

    success_url = reverse_lazy('persona_app:list_admin')   

    def post(self, request, *args, **kwargs):
        #en el metodo post recupera datos enviados al servidor, y funciona en forma de diccionario de python
        dato_a_recuperar = request.POST["last_name"]
        print(dato_a_recuperar)

        return super().post(request, *args, **kwargs)


class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "Persona/deleteview.html"
    success_url = reverse_lazy('persona_app:list_admin')

    def delete(self, request, *args, **kwargs):
        recuperar = request.POST["first_name","last_name"]
                                        
        return super(EmpleadoDeleteView).delete(request, *args, **kwargs)

empleado/templates/persona/agregar.html
{% extends 'base.html' %}


{% block titulo %} Agregar empleado {% endblock titulo %}
    

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar nuevo empleado</h1>

        <form method="post" class="cell callout grid-x grid-margin-x" enctype="multipart/form-data">{% csrf_token %}
            <div class="large-6 cell">
                <label>Nombres
                    {{ form.first_name }}
                </label>
            </div>
            <div class="large-6 cell">
                <label>Apellidos
                    {{ form.last_name }}
                </label>
            </div>
            <div class="large-6 cell">
                <label>Trabajo
                    {{ form.job }}
                </label>
            </div>
            <div class="large-6 cell">
                <label>Departamento
                    {{ form.departamento }}
                </label>
            </div>
            <div class="large-6 cell">
                <label>Habilidades
                    {{ form.habilidades }}
                </label>
            </div>
            <div class="large-6 cell">
                <label>Hoja de vida
                    {{ form.hoja_vida }}
                </label>
            </div>
            <div class="large-6 cell">
                <label>Foto
                    {{ form.imagen }}
                </label>
            </div>
            <div class="cell">
                <button type="submit" class="submit success button">Registrar</button>
            </div>  
            
        </form>
               
    </div>

</div>

{% endblock content %}
    

empleado/templates/persona/deleteview.html
{% extends 'base.html' %}


{% block titulo %} Eliminar empleado {% endblock titulo %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar empleado: {{ object.full_name }}</h1>
        <div class="cell">
            <form method="post">{% csrf_token %}
                <div class="callout alert">
                    <h5>Desea eliminar este empleado?</h5>
                    <p>Advertencia! al eliminar perdera todos los datos de este empleado!</p>
                    <button type="submit" class="alert button" >confirmar</button>
                  </div>                                
            </form>
        </div>

    </div>
</div>

{% endblock content %}
    
    

empleado/templates/persona/detailview.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %} {{ object.full_name }} {% endblock titulo %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x align-center">
    
    <div class="cell large-6 card" style="width: 300px; margin-top: 10px;">
      <div class="card-divider">
        <h1 class="cell">{{ empleado.get_job_display }}</h1>
      </div>        
        {% if empleado.imagen %}
        <img src="{{ empleado.imagen.url }}">
        {% else %}
        <img src="{% static 'img/empleados1.jpg' %}">  
        {% endif %}
        
      <div class="card-section" style="text-align: center;">
        <h4>{{ empleado.full_name }}</h4>            
        <p> Area de: {{ empleado.departamento.short_name }}</p>
        <p><span class="label">Habilidades:</span></p>
        <ul class="vertical menu">
          
          {% for h in empleado.habilidades.all %}
            <li>{{ h }}</li>
          {% endfor %}
            
        </ul>
    
      </div>
    </div>

  </div>
    
</div>

{% endblock content %}

empleado/templates/persona/habilidades.html
<h1>listar habilidades de empleado</h1>

<form method="get"> {% csrf_token %}
    <label for="">ingrese el apellido del empleado</label>
    <input type="text" name="kword" id="kword">
    <button type="submit">Buscar</button>

</form>

<ul>
{% for e in hability %}
    <li>{{ e }}</li>
{% endfor %}
</ul>    

empleado/templates/persona/list_all.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %} Lista de empleados {% endblock titulo %}

{% block content%}
{% include "includes/header.html" %}

    <div class="grid-container">
        <div class="grid-x">
            <h1>Lista de empleados</h1>
            <form class="cell grid-x grid-margin-x" method="get">{% csrf_token %}
                <div class="cell large-8">
                    <input type="text" name="kword" id="kword" placeholder="Buscar empleado">
                </div>
                <div class="cell large-3">
                    <button type="submit" class="submit success button">Buscar</button>
                </div>                                
            </form>
            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">ID</th>
                        <th width="200">Nombre</th>
                        <th width="200">Apellido</th>
                        <th width="200">Departamento</th>
                        <th width="200">Accion</th>
                      </tr>
                    </thead>
                    <tbody>
                        
                        {% for empleados in object_list %}                                                                                
                      <tr>
                        <td>{{ empleados.id }}</td>
                        <td>{{ empleados.first_name }}</td>
                        <td>{{ empleados.last_name }}</td>
                        <td>{{ empleados.departamento}}</td>
                        <td><a href="{% url 'persona_app:detalle-empleado' empleados.id %}" class="button small">Ver</a></td>
                      </tr>
                        {% endfor %}                
                    </tbody>
                </table>
            </div>
            <div class="cell">
                
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination text-center">                        
                        {% if page_obj.has_previous  %}
                        <li class="pagination-previous">
                            <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                        </li>                            
                        {% endif %}
                        
                        {% for pagina in paginator.page_range %}
                                                
                        
                        
                        <li><a href="?page={{ pagina }}" aria-label="Page 2">{{ pagina }}</a></li>                                                                                                    
                        
                        {% endfor %}                                                
                        <!--<li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li> -->
                        
                        {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Siguiente</a>
                        </li>                            
                        {% endif %}
                                
                    </ul>
                </nav>    
                {% endif %}
                    
                
            </div>
        </div>
    </div>
{% endblock content %}

empleado/templates/persona/list_all_admin.html
{% extends 'base.html' %}


{% block titulo %} Empleado Admin {% endblock titulo %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1>Administrador de empleados</h1>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th width="200">Nombre</th>
                    <th width="200">Apellido</th>
                    <th width="200">Departamento</th>
                    <th width="200">Accion</th>
                  </tr>
                </thead>
                <tbody>
                    
                    {% for empleados in object_list %}                                                                                
                  <tr>
                    <td>{{ empleados.id }}</td>
                    <td>{{ empleados.first_name }}</td>
                    <td>{{ empleados.last_name }}</td>
                    <td>{{ empleados.departamento}}</td>
                    <td>
                        <a href="{% url 'persona_app:modificar_empleado' empleados.id %}" class="button small success">Editar</a>
                        <a href="{% url 'persona_app:borrar-empleado' empleados.id %}" class="button small warning">Eliminar</a>
                    </td>
                  </tr>
                    {% endfor %}                
                </tbody>
            </table>
        </div>
        <div class="cell">
            
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination text-center">                        
                    {% if page_obj.has_previous  %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>                            
                    {% endif %}
                    
                    {% for pagina in paginator.page_range %}
                                            
                    
                    
                    <li><a href="?page={{ pagina }}" aria-label="Page 2">{{ pagina }}</a></li>                                                                                                    
                    
                    {% endfor %}                                                
                    <!--<li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li> -->
                    
                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Siguiente</a>
                    </li>                            
                    {% endif %}
                            
                </ul>
            </nav>    
            {% endif %}
                
            
        </div>
    </div>
</div>

{% endblock content %}
    

empleado/templates/persona/list_by_departamento.html
{% extends 'base.html' %}


{% block titulo %} Empleados de area {% endblock titulo %}
    

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid x">
        <div class="cell">
            <table>
                <thead>
                    <tr>
                      <th width="200">ID</th>
                      <th width="200">Nombre</th>
                      <th width="200">Apellido</th>
                      <th width="200">Departamento</th>
                      <th width="200">Accion</th>
                    </tr>
                  </thead>
                  <tbody>
                      
                      {% for empleado in empleados %}                                                                                
                    <tr>
                      <td>{{ empleado.id }}</td>
                      <td>{{ empleado.first_name }}</td>
                      <td>{{ empleado.last_name }}</td>
                      <td>{{ empleado.departamento}}</td>
                      <td><a href="{% url 'persona_app:detalle-empleado' empleado.id %}" class="button small">Ver</a></td>
                    </tr>
                      {% endfor %}                
                  </tbody>                       
            </table>

        </div>

    </div>

</div>
{% endblock content %}
    

empleado/templates/persona/list_por_trabajo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Listar empleados por trabajo</h1>

    <ul>
        
        {% for e in list %}

            <li>{{ e }}</li>
            
        {% endfor %}
            
    </ul>
    
</body>
</html>

empleado/templates/persona/por_kword.html
<h1>listar empleados por keyword</h1>

<form method="get"> {% csrf_token %}
    <label for="">ingrese palabra clave</label>
    <input type="text" name="kword" id="kword">
    <button type="submit">Buscar</button>
    
</form>

<ul>
    
    {% for e in array_kword  %}

    <li>{{ e }}</li>
        
    {% endfor %}
        
</ul>
    

empleado/templates/persona/success.html
<h1>Felicidades el registro fue exitoso</h1>

empleado/templates/persona/update.html
{% extends 'base.html' %}


{% block titulo %} Modificar empleado {% endblock titulo %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Modificar empleado</h1>
        <div class="cell">
            <form method="post" class="grid-x grid-margin-x">{% csrf_token %}
                <div class="large-6 cell">
                    <label>Nombres
                        {{ form.first_name }}
                    </label>
                  </div>
                <div class="large-6 cell">
                    <label>Apellidos
                        {{ form.last_name }}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Trabajo
                        {{ form.job }}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Departamento
                        {{ form.departamento }}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Habilidades
                        {{ form.habilidades }}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Hoja de vida
                        {{ form.hoja_vida }}
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="submit success button">Actualizar</button>
                </div>  
                
            </form>
        </div>

    </div>

</div>

{% endblock content %}
    
{{ form.as_p }}