empleado/aplications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "departamento_app"

urlpatterns = [
    path("new-departamento",
    views.NewDepartamentoView.as_view(),
    name="nuevo-depa"
    ),
    path("lista-by-departamento",
    views.DepartamentoListView.as_view(),
    name="lista-por-depa"
    ),
]

empleado/aplications/persona/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = "persona_app" 

urlpatterns = [
    path(
        "",
        views.InicioView.as_view(),
        name="inicio"
    ),
    path(
        "listar-empleados",
        views.MostrarEmpleados.as_view(),
        name="listar-all"        
    ),
    path("listar-por-departamento/<shorname>",
        views.listar_por_area.as_view(),
        name="empleado-departamento"
    ),
    path("list_all_admin",
        views.MostrarEmpleadosAdmin.as_view(),
        name="list_admin"
    ),
    path("listar-por-trabajo/<laburo>",views.listar_por_trabajo.as_view()),
    path("listar_por_kword/",views.listar_empleado_por_keyword.as_view()),
    path("listar_habilidad/",views.Habilidades_de_Empleados.as_view()),
    path(
        "detalle-vista/<pk>",
        views.EmpleadoDetailView.as_view(),
        name="detalle-empleado"
    ),
    path("agregar-empleado",
    views.EmpleadoCreateView.as_view(),
    name="add-empleado"
    ),
    path("success",views.Successview.as_view(),name="correcto"),
    path("update-empleado/<pk>",
        views.EmpleadoUpdateView.as_view(),
        name="modificar_empleado"
    ),
    path("delete-empleado/<pk>",
    views.EmpleadoDeleteView.as_view(),
    name="borrar-empleado")

]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path,include
#para añadir las urls multimedia
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('aplications.persona.urls')),
    path('',include('aplications.prueba_form.urls')),
    path('',include('aplications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

empleado/aplications/departamento/models.py
from django.db import models

# Create your models here.

class Departamento(models.Model):

    name = models.CharField("Nombre",max_length=30,)
    short_name = models.CharField("Nombre abreviado",max_length=20)
    anulate = models.BooleanField("Anulado",default=False)

    class Meta:
        verbose_name = "Controlador de Departamento"
        ordering = ["id"]    

    def __str__(self):
        return str(self.id) + "-" + self.name + "-" + self.short_name 

empleado/aplications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellido = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=30)
    shorname = forms.CharField(max_length=20)
        

   

empleado/aplications/departamento/views.py
from django.shortcuts import render
from .forms import NewDepartamentoForm
from django.views.generic.edit import FormView
from django.views.generic import ListView
from aplications.persona.models import Empleado
from .models import Departamento
# Create your views here.


class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/listview_depa.html"
    context_object_name = "depas"


class NewDepartamentoView(FormView):
    template_name = "departamento/new_departamento.html"
    form_class = NewDepartamentoForm
    success_url = "/"

    def form_valid(self, form):

        depa = Departamento(
            name = form.cleaned_data["departamento"],
            short_name = form.cleaned_data["shorname"]
        )
        depa.save()

        #recuperar los datos del formulario
        nombre = form.cleaned_data["nombre"]
        apellido = form.cleaned_data["apellido"]
        #hacer registro en el modelo empleado
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellido,
            job = "1",
            departamento = depa,
            hoja_vida = "creado por la funcion new"
        )
        
        return super(NewDepartamentoView,self).form_valid(form) 

empleado/templates/departamento/listview_depa.html
{% extends 'base.html' %}

{% block titulo %} Listado por departamento {% endblock titulo %}

{% block content %}

{% include 'includes/header.html'%}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de departamentos</h1>
    </div>
    <div class="cell">
        <table>
            <tbody>
                {% for departamentos in depas %}
                <tr>
                    <td>{{ departamentos.name }}</td>
                    <td>{{ departamentos.short_name }}</td>
                    <td>
                        <a href="{% url 'persona_app:empleado-departamento' departamentos.short_name %}" class="button small">Ver Empleados</a>
                    </td>
                </tr>
                {% endfor %}                    
                    
            </tbody>
        </table>
    </div>

</div>

{% endblock content %}

empleado/templates/departamento/new_departamento.html
{% extends 'base.html' %}


{% block titulo %} Agregar departamento {% endblock titulo %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Añadir departamento</h1>

        <form class="cell callout grid-x grid-margin-x" method="post">{% csrf_token %}
            <div class="large-6 cell">
                <label>Nombres:
                    {{ form.nombre }}
                </label>
            </div>
            <div class="large-6 cell">
                <label>Apellidos:
                    {{ form.apellido }}
                </label>
            </div>
            <div class="large-6 cell">
                <label>Departamento:
                    {{ form.departamento }}
                </label>
            </div>
            <div class="large-6 cell">
                <label>nombre corto:
                    {{ form.shorname }}
                </label>
            </div>
            <div class="cell">
                <button type="submit" class="submit success button">Registrar</button>
            </div> 
        </form>

    </div>

</div>

{% endblock content %}
    
    


<h1>registro de nuevo departamento</h1>

<form method="post">{% csrf_token %}
    <h3>Datos de empleado</h3>
    <p>
        {{ form.nombre }}
    </p>
    <p>
        {{ form.apellido}}
    </p>
    <h3>Datos Departamento</h3>
    <p>
        {{ form.departamento }}
    </p>
    <p>
        {{ form.shorname }}
    </p>
    <button type="submit">Guardar</button>

</form>